version: '3.2'

services:
    zookeeper:
        image: wurstmeister/zookeeper:latest
        environment:
             ZOOKEEPER_CLIENT_PORT:
              "2181"
        ports:
            - 2181:2181
            - 2888:2888
            - 3888:3888

    kafka1:
        image: wurstmeister/kafka:latest
        build: .
        ports:
            - "9092:9092"
        environment:
             KAFKA_ADVERTISED_LISTENERS:
                "INSIDE://kafka1:9090,OUTSIDE://localhost:9092"
             KAFKA_LISTENERS:
                "INSIDE://kafka1:9090,OUTSIDE://0.0.0.0:9092"
             KAFKA_LISTENER_SECURITY_PROTOCOL_MAP:
                "INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT"
             KAFKA_ZOOKEEPER_CONNECT:
                "zookeeper:2181"
             KAFKA_INTER_BROKER_LISTENER_NAME:
                INSIDE

    kafka2:
        image: wurstmeister/kafka:latest
        build: .
        ports:
            - "9093:9092"
        environment:
             KAFKA_ADVERTISED_LISTENERS:
                "INSIDE://kafka2:9090,OUTSIDE://localhost:9093"
             KAFKA_LISTENERS:
                "INSIDE://kafka2:9090,OUTSIDE://0.0.0.0:9092"
             KAFKA_LISTENER_SECURITY_PROTOCOL_MAP:
                "INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT"
             KAFKA_ZOOKEEPER_CONNECT:
                "zookeeper:2181"
             KAFKA_INTER_BROKER_LISTENER_NAME:
                INSIDE
    kafka3:
        image: wurstmeister/kafka:latest
        build: .
        ports:
            - "9094:9092"
        environment:
             KAFKA_ADVERTISED_LISTENERS:
                "INSIDE://kafka3:9090,OUTSIDE://localhost:9094"
             KAFKA_LISTENERS:
                "INSIDE://kafka3:9090,OUTSIDE://0.0.0.0:9092"
             KAFKA_LISTENER_SECURITY_PROTOCOL_MAP:
                "INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT"
             KAFKA_ZOOKEEPER_CONNECT:
                "zookeeper:2181"
             KAFKA_INTER_BROKER_LISTENER_NAME:
                INSIDE
